state:
  initial: {}
  stateNodeName: playground
components:
  App:
    state-to-props: {}
    view:
      tag: div
      children:
        - tag: Appbar
        - tag: main
          children:
            - tag: NavRoutes
              props: {}
